version: 2
enable-beta-ecosystems: true # needed for uv
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci: github: "
    labels: []
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci: python: "
    labels: []
    groups:
      python-deps:
        patterns:
          - "*"
