# Let CodeCov post a comment in PRs for the coverage of changes.

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  branches:
    - "main"
