language: python
# TODO: 3.7 and 3.8 need testing here.
python:
  - 3.6                         # minimum supported version

build:
  pre_ci_boot:
    image_name: zephyrprojectrtos/ci
    image_tag: v0.10.1
    pull: true
    options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"
  ci:
    - type -p python3
    - python3 --version
    - export PATH=$PATH:$HOME/.local/bin
    - pip3 install tox
    - mkdir -p shippable/{testresults,codecoverage}
    - tox -- --junitxml=$PWD/shippable/testresults/nosetests.xml --cov=west --cov-report=xml:$PWD/shippable/codecoverage/coverage.xml tests
