language: python
# TODO: 3.7 is failing. It'd be good to figure this out eventually as
# it's the latest version which is likely what Windows and macOS users
# run on, but is left out for now.
python:
  - 3.4                         # minimum supported version
  - 3.5                         # ubuntu 16.04
  - 3.6                         # ubuntu 18.04

build:
  ci:
    - pip install --upgrade pip setuptools
    - pip install tox
    - mkdir -p shippable/{testresults,codecoverage}
    - tox -- --junitxml=$PWD/shippable/testresults/nosetests.xml --cov=west --cov-report=xml:$PWD/shippable/codecoverage/coverage.xml tests
