//! Integration tests for `west config migrate`.
//!
//! Each test writes a v1 INI file in a tempdir and runs the binary
//! against it. `--local` paths off the workspace; the `--from PATH
//! --file PATH` pairing covers the non-local scopes without touching
//! `/etc/westconfig` / `~/.westconfig` for real.

use std::path::Path;

use assert_cmd::Command;
use serial_test::serial;
use tempfile::TempDir;

const BIN: &str = "west";

struct Sandbox {
    _tmp: TempDir,
    workspace: std::path::PathBuf,
    v1_local: std::path::PathBuf,
    v2_local: std::path::PathBuf,
}

impl Sandbox {
    fn new() -> Self {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path().join("ws");
        std::fs::create_dir_all(workspace.join(".west")).unwrap();
        // West marker file so topdir() resolves to `workspace`.
        std::fs::write(workspace.join(".west").join("config.toml.placeholder"), "").ok();
        let v1_local = workspace.join(".west").join("config");
        let v2_local = workspace.join(".west").join("config.toml");
        Sandbox {
            _tmp: tmp,
            workspace,
            v1_local,
            v2_local,
        }
    }

    fn west(&self) -> Command {
        let mut c = Command::cargo_bin(BIN).unwrap();
        // `--local` finds the v1 source via topdir from cwd and the v2
        // target via the same topdir; `--from PATH --file PATH` tests
        // sidestep both. HOME is pinned so the v1 global resolver
        // doesn't see the developer's real `~/.westconfig`. XDG is
        // unset for the same reason.
        //
        // `WEST_CONFIG_{LOCAL,GLOBAL,SYSTEM}` are intentionally unset
        // here. The v1 resolver doesn't consult them (we dropped that
        // after seeing it conflicted with v2's meaning for the same
        // env vars). The no-scope mode test is the only spot that
        // could pick up `/etc/westconfig` etc. on a dirty dev box;
        // that's an accepted, narrow exposure.
        c.current_dir(&self.workspace)
            .env_remove("WEST_CONFIG_LOCAL")
            .env_remove("WEST_CONFIG_GLOBAL")
            .env_remove("WEST_CONFIG_SYSTEM")
            .env("HOME", self._tmp.path())
            .env_remove("XDG_CONFIG_HOME");
        c
    }
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_default()
}

#[test]
#[serial]
fn round_trip_basic_keys() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[manifest]\npath = zephyr\nfile = west.yml\n\n[update]\njobs = 8\n",
    )
    .unwrap();

    sb.west()
        .args(["config", "migrate", "--local"])
        .assert()
        .success();

    let toml = read(&sb.v2_local);
    assert!(toml.starts_with("# Generated by `west config migrate` (west "));
    assert!(toml.contains("path = \"zephyr\""));
    assert!(toml.contains("file = \"west.yml\""));
    // Known-int key coerces to a bare integer, not a string.
    assert!(toml.contains("jobs = 8"));
    assert!(!toml.contains("jobs = \"8\""));
    // v1 file untouched.
    assert!(sb.v1_local.exists());
}

#[test]
#[serial]
fn bool_coercion_via_yes_and_aliases() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[update]\nrebase = yes\nkeep-descendants = NO\nnarrow = on\n",
    )
    .unwrap();

    sb.west()
        .args(["config", "migrate", "--local"])
        .assert()
        .success();

    let toml = read(&sb.v2_local);
    assert!(toml.contains("rebase = true"));
    assert!(toml.contains("keep-descendants = false"));
    assert!(toml.contains("narrow = true"));
}

#[test]
#[serial]
fn list_coercion_comma_split() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[manifest]\ngroup-filter = +foo, -bar , +baz\n",
    )
    .unwrap();

    sb.west()
        .args(["config", "migrate", "--local"])
        .assert()
        .success();

    let toml = read(&sb.v2_local);
    // toml_edit may render either inline-array or one-line; the values
    // are what we care about.
    assert!(toml.contains("\"+foo\""), "got {toml}");
    assert!(toml.contains("\"-bar\""));
    assert!(toml.contains("\"+baz\""));
}

#[test]
#[serial]
fn rewrite_update_fetch_to_strategy() {
    let sb = Sandbox::new();
    std::fs::write(&sb.v1_local, "[update]\nfetch = smart\n").unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("update.fetch renamed to tool.git.fetch.strategy"),
        "stderr was: {stderr}"
    );

    let toml = read(&sb.v2_local);
    assert!(toml.contains("strategy = \"smart\""));
    // Old v1 key should not appear in the v2 output.
    assert!(!toml.contains("[update]"));
}

#[test]
#[serial]
fn rewrite_sync_submodules_splits_to_two_bools() {
    let sb = Sandbox::new();
    std::fs::write(&sb.v1_local, "[update]\nsync-submodules = yes\n").unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("tool.git.submodules.sync + tool.git.submodules.recurse"),
        "stderr was: {stderr}"
    );

    let toml = read(&sb.v2_local);
    // Both v2 keys land as native bools.
    assert!(toml.contains("sync = true"), "got: {toml}");
    assert!(toml.contains("recurse = true"), "got: {toml}");
}

#[test]
#[serial]
fn unknown_key_preserved_as_string_with_warning() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[custom]\nlocal-only = hello\n",
    )
    .unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("custom.local-only") && stderr.contains("not recognised"),
        "stderr was: {stderr}"
    );

    let toml = read(&sb.v2_local);
    assert!(toml.contains("local-only = \"hello\""));
}

#[test]
#[serial]
fn bool_coercion_failure_falls_back_to_string() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[update]\nrebase = sometimes\n",
    )
    .unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("expected boolean"), "stderr was: {stderr}");

    let toml = read(&sb.v2_local);
    assert!(toml.contains("rebase = \"sometimes\""));
}

#[test]
#[serial]
fn refuses_to_overwrite_without_force() {
    let sb = Sandbox::new();
    std::fs::write(&sb.v1_local, "[manifest]\npath = zephyr\n").unwrap();
    std::fs::write(&sb.v2_local, "# existing v2 content\n").unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    // Returns non-zero (FAILURE) because the only requested scope was skipped.
    assert!(!out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("already exists"), "stderr was: {stderr}");

    // v2 file is unchanged.
    assert_eq!(read(&sb.v2_local), "# existing v2 content\n");
}

#[test]
#[serial]
fn force_overwrites_existing() {
    let sb = Sandbox::new();
    std::fs::write(&sb.v1_local, "[manifest]\npath = zephyr\n").unwrap();
    std::fs::write(&sb.v2_local, "# stale\n").unwrap();

    sb.west()
        .args(["config", "migrate", "--local", "--force"])
        .assert()
        .success();

    let toml = read(&sb.v2_local);
    assert!(!toml.contains("# stale"));
    assert!(toml.contains("path = \"zephyr\""));
}

#[test]
#[serial]
fn dry_run_writes_nothing_prints_body() {
    let sb = Sandbox::new();
    std::fs::write(&sb.v1_local, "[manifest]\npath = zephyr\n").unwrap();
    assert!(!sb.v2_local.exists());

    let out = sb
        .west()
        .args(["config", "migrate", "--local", "--dry-run"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("would write to"));
    assert!(stdout.contains("path = \"zephyr\""));
    assert!(!sb.v2_local.exists(), "v2 file must not exist after --dry-run");
}

#[test]
#[serial]
fn malformed_default_section_errors() {
    let sb = Sandbox::new();
    std::fs::write(
        &sb.v1_local,
        "[DEFAULT]\nfoo = bar\n[manifest]\npath = zephyr\n",
    )
    .unwrap();

    let out = sb
        .west()
        .args(["config", "migrate", "--local"])
        .output()
        .unwrap();
    assert!(!out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("DEFAULT"), "stderr was: {stderr}");
    assert!(!sb.v2_local.exists());
}

#[test]
#[serial]
fn from_path_with_file_target() {
    // `--from PATH --file PATH` decouples source from target; used by
    // tests + users with non-conventional layouts.
    let tmp = TempDir::new().unwrap();
    let v1 = tmp.path().join("oldconfig");
    let v2 = tmp.path().join("newconfig.toml");
    std::fs::write(&v1, "[manifest]\npath = zephyr\n").unwrap();

    let mut c = Command::cargo_bin(BIN).unwrap();
    c.args([
        "config",
        "migrate",
        "--from",
        v1.to_str().unwrap(),
        "--file",
        v2.to_str().unwrap(),
    ])
    // Keep the test hermetic — no ambient layer files.
    .env_remove("WEST_CONFIG_LOCAL")
    .env_remove("WEST_CONFIG_GLOBAL")
    .env_remove("WEST_CONFIG_SYSTEM")
    .env("HOME", tmp.path())
    .env_remove("XDG_CONFIG_HOME");
    c.assert().success();

    let toml = read(&v2);
    assert!(toml.contains("path = \"zephyr\""));
}

#[cfg(target_os = "linux")]
#[test]
#[serial]
fn linux_global_falls_back_to_dotwestconfig_when_xdg_path_absent() {
    // Linux-only: when XDG_CONFIG_HOME is set but no file exists at
    // `$XDG_CONFIG_HOME/west/config`, the v1 resolver should still find
    // `~/.westconfig` if the user has one there. (v1.5.0 didn't fall
    // back; we deviate intentionally — see comment in v1_global_default.)
    let tmp = TempDir::new().unwrap();
    // XDG_CONFIG_HOME is set but the file at $XDG_CONFIG_HOME/west/config
    // doesn't exist — only the directory needs to (so v2 can write its
    // .toml output into it without create_dir_all racing the test).
    let xdg = tmp.path().join("xdg-home");
    std::fs::create_dir_all(xdg.join("west")).unwrap();
    let home = tmp.path().join("home");
    std::fs::create_dir(&home).unwrap();
    let westconfig = home.join(".westconfig");
    std::fs::write(&westconfig, "[manifest]\npath = via-fallback\n").unwrap();

    let v2_global = xdg.join("west").join("config.toml");

    let mut c = Command::cargo_bin(BIN).unwrap();
    c.args(["config", "migrate", "--global"])
        // XDG sets BOTH the would-be v1 path ($XDG/west/config — absent)
        // AND v2's write target ($XDG/west/config.toml — gets created by
        // the migration). Leaving WEST_CONFIG_GLOBAL unset is what makes
        // the v1 resolver actually exercise v1_global_default, the code
        // under test.
        .env("XDG_CONFIG_HOME", &xdg)
        .env("HOME", &home)
        .env_remove("WEST_CONFIG_LOCAL")
        .env_remove("WEST_CONFIG_GLOBAL")
        .env_remove("WEST_CONFIG_SYSTEM");
    c.assert().success();

    let body = read(&v2_global);
    assert!(
        body.contains("path = \"via-fallback\""),
        "expected migration to read ~/.westconfig via fallback, got: {body}"
    );
}

#[test]
#[serial]
fn no_v1_files_anywhere_is_a_warning_not_error() {
    let sb = Sandbox::new();
    // No v1 file written.
    let out = sb
        .west()
        .args(["config", "migrate"])
        .output()
        .unwrap();
    assert!(out.status.success());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("no v1 config"), "stderr was: {stderr}");
}
