[package]
name = "west-cli"
version = "2.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rayon = "1"
shlex = "1"
west-core = { path = "../west-core" }

[dev-dependencies]
assert_cmd = "2"
serial_test = "3"
tempfile = "3"

[[bin]]
name = "west"
