# SPDX-License-Identifier: Apache-2.0

x-common: &common
  user: ${MY_UID}:${MY_GID}
  volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - ..:/west
  command: /west/docker-testing/in-container-test.sh
  environment:
    WEST_TOX_OUT: /west/docker-testing/outdir
    WEST_TOX_OUT_IN_HOST: ${WEST_IN_HOST}/docker-testing/outdir

services:
  west-archlinux-latest:
    <<: *common
    build:
      args:
        TARGET: archlinux:latest
      dockerfile: arch/Dockerfile

  west-debian-stable:
    <<: *common
    build:
      args:
        TARGET: debian:stable
      dockerfile: debian/Dockerfile

  west-debian-testing:
    <<: *common
    build:
      args:
        TARGET: debian:testing
      dockerfile: debian/Dockerfile

  west-fedora-latest:
    <<: *common
    build:
      args:
        TARGET: fedora:latest
      dockerfile: fedora/Dockerfile

  west-fedora-rawhide:
    <<: *common
    build:
      args:
        TARGET: fedora:rawhide
      dockerfile: fedora/Dockerfile

  west-ubuntu-latest:
    <<: *common
    build:
      args:
        TARGET: ubuntu:latest
      dockerfile: debian/Dockerfile

  west-ubuntu-devel:
    <<: *common
    build:
      args:
        TARGET: ubuntu:devel
      dockerfile: debian/Dockerfile
